theme: jekyll-theme-minimal

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn clean
          - mvn -B verify # -B batch mode makes Maven less verbose
          - mvn install assembly:single
